### ISSUE TITLE
release version 1.12.0

### ISSUE THREAD

**Issue by schengawegga** [pear/DB#20]
prepare and release version 1.12.0

**Comment by guilheb** [comment]
Curious, when is 1.12.0 planned?

**Comment by schengawegga** [comment]
@guilheb in wich PR you are interested? I plan to split the versions a bit, because of setting the `getVersion()` Method as static, wich changes the behavior of the package and results in a new major version, to keep it backwards-compatible.

**Comment by guilheb** [comment]
@schengawegga I'm only looking for PHP 8.2 compatibility

**Comment by schengawegga** [comment]
@guilheb i´ve done a PR #21 to become fully PHP8.2 ready. After verifying this PR, i will release the version 1.12.0.

**Comment by ashnazg** [comment]
#21 is merged now, @schengawegga

**Comment by demeritcowboy** [comment]
@schengawegga Does your comment earlier about getVersion refer to https://github.com/pear/DB/pull/17 and you'd like to leave that out of 1.12.0? For me the answer to "in which PR you are interested" is that I would be interested in all of them.

Thanks for everyone's work keeping this package updated!

**Comment by MarkMaldaba** [comment]
> @guilheb in wich PR you are interested? I plan to split the versions a bit, because of setting the `getVersion()` Method as static, wich changes the behavior of the package and results in a new major version, to keep it backwards-compatible.

I don't think this is correct, is it?  Labelling a method as static does not prevent it from being called in a non-static context, but just prevents errors being raised in a static context on more recent PHP versions.

In other words, `$obj->apiVersion()` will still work just fine.

As per PR #17:
> Note that this change will not break any misbehaving code that is instantiating the DB class in order to call this method - it is quite acceptable to call a static function on an object instance.

Therefore this should not prevent a 1.12 release.

**Comment by wideareashb** [comment]
Can this be released?

**Comment by schengawegga** [comment]
Thanks for all your comments. I am very busy at the moment. I will have a look at it next week.

**Comment by schengawegga** [comment]
> > @guilheb in wich PR you are interested? I plan to split the versions a bit, because of setting the `getVersion()` Method as static, wich changes the behavior of the package and results in a new major version, to keep it backwards-compatible.
> 
> I don't think this is correct, is it? Labelling a method as static does not prevent it from being called in a non-static context, but just prevents errors being raised in a static context on more recent PHP versions.
> 
> In other words, `$obj->apiVersion()` will still work just fine.
> 
> As per PR #17:
> 
> > Note that this change will not break any misbehaving code that is instantiating the DB class in order to call this method - it is quite acceptable to call a static function on an object instance.
> 
> Therefore this should not prevent a 1.12 release.

you´re right. but the minor release is because of  "Add Driver SQLite3 #18" , too

**Comment by wideareashb** [comment]
So does that mean that this can be released as 1.12.1

**Comment by schengawegga** [comment]
@wideareashb no, it will be released as 1.12.0. I will do this in the next days. But before, i will do a quick test to check the compatibility with PHP 5.0. If we need to update the dependencies, too.

**Comment by schengawegga** [comment]
Version 1.12.0 released

**Comment by Neustradamus** [comment]
@schengawegga: Good job!

**Comment by Neustradamus** [comment]
And the 1.12.1 too:
- https://github.com/pear/DB/releases

Thanks @remicollet too.
