### ISSUE TITLE
sqlite3 back-end incorrectly refers to 'resource' objects

### ISSUE THREAD

**Issue by MarkMaldaba** [pear/DB#38]
The sqlite3 back-end looks like it was created by copying and adapting the sqlite back-end.  It therefore contains a lot of references to `resource` in function return types and comments.

However, the [`SQLite3` class](https://www.php.net/manual/en/class.sqlite3.php) class returns an `SQLite3Result` object for all query actions, not a `resource` instance.  This has [always been the case](https://php-legacy-docs.zend.com/manual/php5/en/sqlite3.query) so is not a compatibility issue, just something that was missed when the `DB_sqlite3` class was created.

As far as I can see, the only functional issue outside of the code comments and annotations is that there is an `is_resource()` check in the `freeResult()` function, which means that this function always returns false.  In practice, there is nothing to free, so behaviour of the function is unaffected.  However, any code which is checking the result of `freeResult()` may end up misreporting that an error occurred.

**Comment by schengawegga** [comment]
Thank you @MarkMaldaba . I will have a look at it soon.
